/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.maiconfz.java_solid_design_principles.java-application-conventions")
    id("org.springframework.boot") version "3.1.4"
    id("io.spring.dependency-management") version "1.1.3"
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")

    annotationProcessor("org.projectlombok:lombok")
    
    compileOnly("org.projectlombok:lombok")
    
    developmentOnly("com.h2database:h2:2.2.224")
    developmentOnly("org.springframework.boot:spring-boot-devtools")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

version = "0.0.1-SNAPSHOT"

configurations {
  compileOnly {
    extendsFrom(configurations.annotationProcessor.get())
  }
}

application {
    mainClass.set("io.github.maiconfz.java_solid_design_principles.app.App")
}
